version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
  
  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/docker
    depends_on:
      - db